[workspace]

members = [
    "core/ansinator_cli",
    "core/ansinator_ansi_image",
    "core/ansinator_image_window",
    "core/ansinator_image_binarize",
    "core/ansinator_terminal_colors",
    "core/ansinator_ascii_font",
]
