[package]
name = "ansinator_cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.2.20", features = ["derive"] }
ansi_image = { path = "../ansi_image" }
image = "0.24.3"
